#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory

#------------------------------------------------------------------------------

# 1. Clean the directory src/transportModels/incompressible
wclean src/transportModels/incompressible

# 2. Clean the directory src/transportModels/addTRadConvImmiscibleIncompressibleTwoPhaseMixture
wclean src/transportModels/addTRadConvImmiscibleIncompressibleTwoPhaseMixture

# 3. Remove any libraries created in the platform directories
rm -rf $FOAM_USER_LIBBIN/libaddTRadConvImmiscibleIncompressibleTwoPhaseMixture*
rm -rf $FOAM_USER_LIBBIN/libaddTIncompressibleTransportModels*

# Final message
echo "Cleaning src completed. Codebase restored to the state before compilation."

#------------------------------------------------------------------------------

# 1. Clean the directory applications/solvers/multiphase/interThermalRadConvFoam
wclean applications/solvers/multiphase/interThermalRadConvFoam

# 3. Remove any libraries created in the platform directories
rm -rf $FOAM_USER_APPBIN/interThermalRadConvFoam

# Final message
echo "Cleaning applications completed. Codebase restored to the state before compilation."

#------------------------------------------------------------------------------

